### ISSUE TITLE
Example in singer.py (should this be signer.py? :) ) mixes proof purposes

### ISSUE THREAD

**Issue by dlongley** [mmlab-aueb/PyEd25519Signature2018#1]
While just an example (and perhaps not the focus of the example), I thought it was important to note that the `proofPurpose` used in your example is `assertionMethod` but the "verification relationship" used in the DID Document to express the `verificationMethod` is `authentication`. This is a mismatch that would cause a properly implemented verifier to reject the proof.

The way that "verification relationships" work is that they link a DID subject to a verification method that is authorized for a specific purpose. So, if a proof expresses that it was created for the purpose of "assertionMethod", then a verifier knows to look for the `verificationMethod` expressed in the proof under the "assertionMethod" property in the DID Document. If the verification method cannot be found under that property, then it is not considered authorized to verify the proof and the verifier must emit an error indicating this.

This mechanism allows verifiers to help provide additional security protections for users -- whereby, for example, if the user has signed a message by attaching a proof with a `proofPurpose` of `assertionMethod`, it cannot be misused by an attacker to try and authenticate as the user instead. There's a critical difference between signing a message to "merely make an assertion" and signing a message as a means to authenticate to a service to, for example, establish a session to perform actions you're authorized to do. Ideally, messages themselves help make this distinction, but it is not always the case -- and sometimes encodings can be abused to misrepresent different semantics for the same message payload.

**Comment by nikosft** [comment]
Thanks for the comment. I am wondering if you can help with the following.
The goal of this script is to eventually generate the proof part of a DID document. So the purpose of the poof is to provide integrity. In all proof examples in [Decentralized Identifiers (DIDs) v1.0](https://www.w3.org/TR/did-core/) there is no attribute "purpose". On the other hand [Linked Data Proofs 1.0](https://w3c-ccg.github.io/ld-proofs) seems to consider this attribute mandatory, and indeed digital bazaars implementation throw an exception if not proof is provided. So which should be the proper "purpose" value?

**Comment by dlongley** [comment]
The example in the DID spec is quite old -- and is about to removed :) -- in favor of relying on the Linked Data Proofs spec. Note that most DID methods do not use `proof` -- and for those that do, it may make more sense to wrap the DID Document in an outer envelope that allows for meta-data about the DID Document to be expressed -- and attach a proof to that instead. That way a DID resolver for a method that supported this approach could supply both meta-data and the DID Document.

>  So which should be the proper "purpose" value?

If a `proof` is going to be attached to a DID Document (or a meta-data structure that envelopes it), I would expect `assertionMethod` to be used here as the purpose of the proof is to make assertions about the DID subject (via its DID Document) and any meta-data about DID Document.

**Comment by nikosft** [comment]
Yes, there is a lot of discussion around proofs in DID documents  :) 
In any case I think that the Document in the example is now correct
https://github.com/mmlab-aueb/PyEd25519Signature2018/blob/3fddb3b31f35e4fe60eee28bad1b202d2dd79a5e/signer.py#L27

**Comment by dlongley** [comment]
Yup, looks right!
